services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      MONGO_URI: mongodb+srv://Teddy1224:O%40thk33p3r@chardoneybrewlane.ce45g.mongodb.net/coffee_shop

    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - API_BASE_URL=http://backend:5000
    networks:
      - app-network

  mongo:
    image: mongo:5.0

    restart: always
    ports:
      - "27017:27017" 
    
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge