services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      MONGO_URI: mongodb://mongo:27017/coffee_shop
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:5000/api
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/c/data:/data/db"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge