name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./server  # Set to backend directory
          file: ./server/Dockerfile  # Specify backend Dockerfile path
          push: true
          tags: teddya12/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./client  # Set to frontend directory
          file: ./client/Dockerfile  # Specify frontend Dockerfile path
          push: true
          tags: teddya12/frontend:latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d

